# [[redirects]]
# force = true
# from = '/api/*'
# status = 200
# to = "https://apis.data.go.kr/:splat"

# [[redirects]]
# from = '/*'
# status = 200
# to = '/index.html'

# [build]
# command = 'npm run build'
# environment = {NODE_VERSION = '14'}
# publish = 'dist'

# [dev]
# autoLaunch = false